version: "3.8"

services:
  postgres-db:
    image: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - "./secrets/postgres.env"
  app:
    build:
      context: ./
    image: dins:app
    volumes:
      - ./:/app
    ports:
      - "3000:8080"
    env_file:
      - "./secrets/postgres.env"
    environment:
      - POSTGRES_HOST=postgres-db
    depends_on: [ postgres-db ]
volumes:
  postgres-data: