version: "3.8"

services:
  postgres-db:
    image: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "6432:5432"
    env_file:
      - "./secrets/postgres.env"
  app:
    build:
      context: ./
    image: dins:app
    command: ["--app_mode=consume"]
    volumes:
      - ./:/app
    ports:
      - "3000:8080"
    env_file:
      - "./secrets/postgres.env"
    environment:
      - POSTGRES_HOST=postgres-db
      - KAFKA_HOST=kafka
      - POSTGRES_PORT=5432
      - KAFKA_PORT=9093
    depends_on: [ postgres-db ]
volumes:
  postgres-data: