version: "3.8"

services:
  postgres-db:
    image: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=default
  app:
    build:
      context: ./
    image: dins:app
    user: root
    volumes:
      - ./:/app
      - ./logs:/logs
    ports:
      - "3000:8080"
    environment:
      - POSTGRES_HOST=postgres-db
      - KAFKA_HOST=kafka
      - POSTGRES_PORT=5432
      - KAFKA_PORT=9093
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=default
    depends_on: [ postgres-db ]
volumes:
  postgres-data: